### ISSUE TITLE
Could find classes ImapClientFactoryConfiguration and ImapClientConfiguration

### ISSUE THREAD

**Issue by prakashprem** [HubSpot/NioImapClient#16]
Consider the following file com.hubspot.imap.ImapClientFactory.java

The constructor requires :

```
public ImapClientFactory() {
    this(ImapClientFactoryConfiguration.builder().build());
  }
```

ImapClientFactoryConfiguration class, but it could not be found.

Similary, the same file has the following code:

```
 public CompletableFuture<ImapClient> connect(ImapClientConfiguration clientConfiguration) {
    return connect("unknown-client", clientConfiguration);
  }
```

It requires the class ImapClientConfiguration.java. That class could also not be found. 

These errors occur in lot of places in the code. These two classes could not be found in the source code. Can you please help me fix this ?

**Comment by zklapow** [comment]
Hi @prakashprem how are using the client? Are you pulling in the maven snapshot or checking out the source code locally? Do you know what version you are using?

**Comment by prakashprem** [comment]
I downloaded the source code from the github repo - branch master using the clone or download option. Basically I downloaded the source code as a zip from the github repo.

Thank you,
Prakash

**Comment by zklapow** [comment]
Hey @prakashprem  sorry for the delay in responding, I was on vacation.

Those classes are generated with [immutables](https://immutables.github.io/immutable.html) so I would bet that the immutables annotation processor is not being run. Are you building the code via maven?

Can you try pulling in the code via maven and see if that works for you? This should get you the latest version and should include the generated classes:

```xml
    <dependency>
      <groupId>com.hubspot</groupId>
      <artifactId>NioImapClient</artifactId>
      <version>0.4-SNAPSHOT</version>
    </dependency>
```

**Comment by zklapow** [comment]
Hey @prakashprem I am going to close this out, but let me know if you are still having trouble.

**Comment by prakash-premkumar** [comment]
Hi zklapow. Thanks for your reply. Sorry for reposting after a while. I was working on another project.

I tried adding it via maven. I get 

> Missing artifact com.hubspot:NioImapClient:jar:
>  0.4-SNAPSHOT


Can you please help me fix this ?

**Comment by steve-scorn** [comment]
Artifacts are available here:

https://packages.atlassian.com/maven/com/hubspot/NioImapClient/0.4-SNAPSHOT/
