### ISSUE TITLE
Could not download NioImapClient via Maven : Missing artifact

### ISSUE THREAD

**Issue by prakash-premkumar** [HubSpot/NioImapClient#31]
Hi ,
I'm trying to add NioImapClient as a maven dependency.

I tried 

>     <dependency>
>       <groupId>com.hubspot</groupId>
>       <artifactId>NioImapClient</artifactId>
>       <version>0.4-SNAPSHOT</version>
>     </dependency>

But I get the following error: 

> Missing artifact com.hubspot:NioImapClient:jar:0.4-SNAPSHOT

Can you please help me fix it ?

**Comment by jhaber** [comment]
I think we just need to cut a release of this library and publish it to Maven central, @cimmyv @axiak @brian5021 could someone take care of that?

**Comment by jhaber** [comment]
Sorry for the multi-year delay, I'm sure you moved on long ago. Just wanted to let you know that a release is finally available in Maven central:
```xml
<dependency>
  <groupId>com.hubspot</groupId>
  <artifactId>NioImapClient</artifactId>
  <version>0.4</version>
</dependency>
```
